# Generated by Django 4.2.4 on 2023-09-12 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppLiga", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipo",
            options={"ordering": ("nombre",)},
        ),
        migrations.AlterModelOptions(
            name="jugador",
            options={"verbose_name": "Jugador", "verbose_name_plural": "Jugadores"},
        ),
        migrations.AlterUniqueTogether(
            name="equipo",
            unique_together={("nombre", "liga")},
        ),
    ]
